### PR TITLE
[ISSUE-3142][Improve] Extract the exception utils methods into ExceptionUtils.

### LINKED ISSUE #3142: [Improve] Extract the exception utils methods into ExceptionUtils.
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Extract the exception utils methods into ExceptionUtils.

### Usage Scenario

_No response_

### Related issues

#2986 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by RocMarshal**
## What changes were proposed in this pull request

Issue Number: close #3142 

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (yes / no)

### CODE REVIEW

File: streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/exception/AlertException.java [hunk 1]
```diff
@@ -17,15 +17,15 @@
...
+import org.apache.streampark.common.util.ExceptionUtils;
 
 public class AlertException extends ApiAlertException {
   public AlertException(String message) {
     super(message);
   }
 
   public AlertException(Throwable cause) {
-    super(Utils.stringifyException(cause));
+    super(ExceptionUtils.stringifyException(cause));
```
Comment (wolfboys) [inline streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/exception/AlertException.java:28]: good job👍

File: streampark-common/src/main/java/org/apache/streampark/common/util/ExceptionUtils.java [hunk 2]
```diff
@@ -0,0 +1,24 @@
+package org.apache.streampark.common.util;
```
Comment (wolfboys) [inline streampark-common/src/main/java/org/apache/streampark/common/util/ExceptionUtils.java:18]: Missing license header

**Review by wolfboys — APPROVED** [review]
LGTM
