### PR TITLE
[Bug] after flink 1.15 error when verify SQL script bug fix

### LINKED ISSUE #1713: [Bug] Error When Verify SQL Script
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When click verify button in the web ui, an exception will appear. I guess that may because something wrong in the maven dependency?

### StreamPark Version

git clone the latest

### Java Version

1.8.0_291

### Flink Version

1.15.0

### Scala Version of Flink

2.12

### Error Exception

```
java.lang.ClassNotFoundException: org.apache.flink.table.planner.parse.CalciteParser at java.net.URLClassLoader.findClass(URLClassLoader.java:382) at java.lang.ClassLoader.loadClass(ClassLoader.java:418) at org.apache.streampark.flink.proxy.ChildFirstClassLoader.super$loadClass(ChildFirstClassLoader.scala:143) at org.apache.streampark.flink.proxy.ChildFirstClassLoader.$anonfun$loadClassWithoutExceptionHandling$3(ChildFirstClassLoader.scala:146) at scala.util.Failure.getOrElse(Try.scala:222) at org.apache.streampark.flink.proxy.ChildFirstClassLoader.loadClassWithoutExceptionHandling(ChildFirstClassLoader.scala:146) at org.apache.streampark.flink.proxy.ChildFirstClassLoader.loadClass(ChildFirstClassLoader.scala:69) at java.lang.ClassLoader.loadClass(ClassLoader.java:351) at java.lang.Class.forName0(Native Method) at java.lang.Class.forName(Class.java:264) at org.apache.streampark.flink.core.FlinkSqlValidator$.$anonfun$verifySql$6(FlinkSqlValidator.scala:95) at scala.util.Failure.getOrElse(Try.scala:218) at org.apache.streampark.flink.core.FlinkSqlValidator$.$anonfun$verifySql$4(FlinkSqlValidator.scala:95) at scala.util.Try$.apply(Try.scala:209) at org.apache.streampark.flink.core.FlinkSqlValidator$.$anonfun$verifySql$2(FlinkSqlValidator.scala:94) at org.apache.streampark.flink.core.FlinkSqlValidator$.$anonfun$verifySql$2$adapted(FlinkSqlValidator.scala:70) at scala.collection.immutable.List.foreach(List.scala:388) at org.apache.streampark.flink.core.FlinkSqlValidator$.verifySql(FlinkSqlValidator.scala:70) at org.apache.streampark.flink.core.FlinkSqlValidator.verifySql(FlinkSqlValidator.scala) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.apache.streampark.console.core.service.impl.FlinkSqlServiceImpl.lambda$verifySql$0(FlinkSqlServiceImpl.java:193) at org.apache.streampark.flink.proxy.FlinkShimsProxy$$anon$1.get(FlinkShimsProxy.scala:80) at org.apache.streampark.common.util.ClassLoaderUtils$.runAsClassLoader(ClassLoaderUtils.scala:58) at org.apache.streampark.flink.proxy.FlinkShimsProxy$.proxy(FlinkShimsProxy.scala:79) at org.apache.streampark.flink.proxy.FlinkShimsProxy.proxy(FlinkShimsProxy.scala) at org.apache.streampark.console.core.service.impl.FlinkSqlServiceImpl.verifySql(FlinkSqlServiceImpl.java:188) at org.apache.streampark.console.core.service.impl.FlinkSqlServiceImpl$$FastClassBySpringCGLIB$$d657a89c.invoke(<generated>) at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) at org.apache.streampark.console.core.service.impl.FlinkSqlServiceImpl$$EnhancerBySpringCGLIB$$1fb59fbe.verifySql(<generated>) at org.apache.streampark.console.core.controller.FlinkSqlController.verify(FlinkSqlController.java:55) at org.apache.streampark.console.core.controller.FlinkSqlController$$FastClassBySpringCGLIB$$e1cd5352.invoke(<generated>) at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:123) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) at org.apache.streampark.console.core.controller.FlinkSqlController$$EnhancerBySpringCGLIB$$eaac4fb1.verify(<generated>) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1070) at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) at javax.servlet.http.HttpServlet.service(HttpServlet.java:517) at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) at javax.servlet.http.HttpServlet.service(HttpServlet.java:584) at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) at io.undertow.websockets.jsr.JsrWebSocketFilter.doFilter(JsrWebSocketFilter.java:173) at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61) at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:450) at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365) at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90) at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83) at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387) at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362) at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) at com.github.xiaoymin.swaggerbootstrapui.filter.SecurityBasicAuthFilter.doFilter(SecurityBasicAuthFilter.java:84) at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) at com.github.xiaoymin.swaggerbootstrapui.filter.ProductionSecurityFilter.doFilter(ProductionSecurityFilter.java:53) at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117) at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275) at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79) at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134) at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131) at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255) at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79) at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100) at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387) at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852) at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019) at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558) at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449) at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282) at java.lang.Thread.run(Thread.java:748)
```

### Screenshots

image

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by monrg**
## What problem does this PR solve?
after flink 1.15 flink-table-planner migrated to opt directory, streampark classloader failed to load the CalciteParser class,  error when verify SQL script ,nedd to  add flink-table-planner to verify sql classloader classpath

Issue Number:close  #1713

Problem Summary:
after flink 1.15  error when verify SQL script

## What is changed and how it works?
Separate the verify sql from the classloader of the submitted job, compatible with multiple versions to get the check sql dependency to create a new classloader, and the submitted job is unchanged.

### CODE REVIEW

File: streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala [hunk 1]
```diff
@@ -57,7 +57,7 @@ object FlinkShimsProxy extends Logger {
    * Get shimsClassLoader to execute for scala API
    *
    * @param flinkVersion flinkVersion
-   * @param func execute function
+   * @param func         execute function
```
Comment (LiebingYu) [inline streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala]: I think this line is no need to be changed.

File: streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala [hunk 2]
```diff
@@ -70,7 +70,7 @@ object FlinkShimsProxy extends Logger {
    * Get shimsClassLoader to execute for java API
    *
    * @param flinkVersion flinkVersion
-   * @param func execute function
+   * @param func         execute function
```
Comment (LiebingYu) [inline streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala]: The same as line 60.

**Review by LiebingYu — COMMENTED** [review]
Except for a few code formatting issues pointed out, I think the functionality of the implementation is OK.

File: streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala (hunk 1 above)
Comment (wolfboys) [reply streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala]: > I think this line is no need to be changed.

+1

File: streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala [hunk 3]
```diff
@@ -88,10 +88,17 @@ object FlinkShimsProxy extends Logger {
 
     SHIMS_CLASS_LOADER_CACHE.getOrElseUpdate(s"${flinkVersion.fullVersion}", {
       // 1) flink/lib
-      val libURL = getFlinkHomeLib(flinkVersion.flinkHome)
-      val shimsUrls = ListBuffer[URL](libURL: _*)
+      def filterLib(filterLib: File): Boolean = {
+        !(filterLib.getName.startsWith("log4j") || filterLib.getName.startsWith("flink-table-planner-loader"))
```
Comment (1996fanrui) [inline streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala]: Why add the `filterLib.getName.startsWith("flink-table-planner-loader"))`?

File: streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala [hunk 4]
```diff
@@ -88,10 +88,17 @@ object FlinkShimsProxy extends Logger {
...
+      }
 
-      // 2) shims jar
+      val libURL = getFlinkHomeLib(flinkVersion.flinkHome, "lib", filterLib)
+      // 2) After version 1.15 need add flink/opt/flink-table-planner*
+      val getFlinkTablePlanner: File => Boolean = _.getName.startsWith("flink-table-planner")
+      val optURL = getFlinkHomeLib(flinkVersion.flinkHome, "opt", getFlinkTablePlanner)
```
Comment (1996fanrui) [inline streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala]: The optURL just includes `opt/flink-table-planner*`, so the `optURL` should be renamed to `tablePlannerURL`?

**Review by 1996fanrui — COMMENTED** [review]
Hi @monrg , thanks for your contribution. I have left some minor comments, please take a look in your free time, thanks~

File: streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala (hunk 3 above)
Comment (monrg) [reply streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala]: Thank you for your feedback，because ExecutorFactory has two implementation: DefaultExecutorFactory(flink-table-planer) and DelegateExecutorFactory(flink-table-planer-loader), spi load 2 servi will conflict, When flink 1.15 running the process is loaded through DelegateExecutorFactory by DefaultExecutorFactory, so exclude flink-table-planer-loader to add flink-table-planer to classpath, this scheme is relatively simple, and later will study whether there can be a better way

File: streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala (hunk 1 above)
Comment (monrg) [reply streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala]: This is the IDEA formatting tool and has been rollback

File: streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala (hunk 4 above)
Comment (monrg) [reply streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala]: This is a better variable name,Has been renamed.

File: streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala (hunk 3 above)
Comment (1996fanrui) [reply streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala]: Hi @monrg , thanks for your clarification, from your information, flink doc and streampark code, I got some background:

1. `FlinkSqlValidator#verifySql` use `org.apache.flink.table.planner.parse.CalciteParser` to verify sql
2. `org.apache.flink.table.planner.parse.CalciteParser` in the `flink-table-planer` module, and flink-1.15 move this module from lib to opt dir. ( Flink doc also describes these information[1])
3. StreamPark add `lib/*`(exclude log4j) to the classpath during verify sql.

So, `org.apache.flink.table.planner.parse.CalciteParser` cannot be found when verify flink-1.15 sql, right?

If yes, I have some concerns:

Current solution exclude `lib/flink-table-planer-loader*` and add `opt/flink-table-planer*` to classpath. It can solve the problem of validating sql, but I'm not sure whether it will introduce new problems during launch job. These code changes now also affect the launch flink job, right?

Flink wants to import all `lib/*` when launch a job.[2] In order to verify the sql, streampark replaces the jar, and streampark users do not know. It could be a risk.

So, I suggest to replace jar when only sql validation. Other processes keep the original logic. What do you think?

image

image


[1] https://nightlies.apache.org/flink/flink-docs-release-1.15/docs/dev/configuration/advanced/#anatomy-of-table-dependencies
[2] https://nightlies.apache.org/flink/flink-docs-release-1.15/docs/dev/configuration/advanced/#anatomy-of-the-flink-distribution

Comment (monrg) [reply streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala]: Thank you for your feedback.Yes, there is a risk in breaking Flink's expected approach, and I'm looking into separating the validation SQL from the submission logic

File: streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala [hunk 5]
```diff
@@ -130,10 +137,10 @@ object FlinkShimsProxy extends Logger {
     })
   }
 
-  private[this] def getFlinkHomeLib(flinkHome: String): List[URL] = {
```
Comment (wolfboys) [inline streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala:133]: The method name can be improved, how about `getFlinkLib` ?

File: streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala [hunk 6]
```diff
@@ -88,10 +88,17 @@ object FlinkShimsProxy extends Logger {
 
     SHIMS_CLASS_LOADER_CACHE.getOrElseUpdate(s"${flinkVersion.fullVersion}", {
       // 1) flink/lib
-      val libURL = getFlinkHomeLib(flinkVersion.flinkHome)
-      val shimsUrls = ListBuffer[URL](libURL: _*)
+      def filterLib(filterLib: File): Boolean = {
```
Comment (wolfboys) [inline streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala]: Difficult to read, It is recommended change to this:
`!lib.getName.startsWith("log4j") && !lib.getName.startsWith("flink-table-planner-loader")`

File: streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala [hunk 7]
```diff
@@ -88,10 +88,17 @@ object FlinkShimsProxy extends Logger {
...
+        !(filterLib.getName.startsWith("log4j") || filterLib.getName.startsWith("flink-table-planner-loader"))
+      }
 
-      // 2) shims jar
+      val libURL = getFlinkHomeLib(flinkVersion.flinkHome, "lib", filterLib)
+      // 2) After version 1.15 need add flink/opt/flink-table-planner*
+      val getFlinkTablePlanner: File => Boolean = _.getName.startsWith("flink-table-planner")
+      val tablePlannerURL = getFlinkHomeLib(flinkVersion.flinkHome, "opt", getFlinkTablePlanner)
```
Comment (wolfboys) [inline streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala]: There is no need to define variables, The code can be further simplified,      
 `val tablePlannerURL = getFlinkHomeLib(flinkVersion.flinkHome, "opt", _.getName.startsWith("flink-table-planner"))`

Comment (monrg) [reply streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala]: hi @wolfboys ,Thank you for your feedback.I revised the implementation again, you can review it again

File: streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala (hunk 3 above)
Comment (monrg) [reply streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala]: hi @1996fanrui  ,Thank you for your feedback.I revised the implementation again, you can review it again

File: streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala [hunk 8]
```diff
@@ -81,59 +83,106 @@ object FlinkShimsProxy extends Logger {
...
+   * @param flinkVersion flinkVersion
+   * @param func         execute function
+   * @tparam T
+   * @return
+   */
+  def proxyVerifySql[T](flinkVersion: FlinkVersion, func: JavaFunc[ClassLoader, T]): T = {
+    val shimsClassLoader = getVerifySqlLibClassLoader(flinkVersion)
+    ClassLoaderUtils.runAsClassLoader[T](shimsClassLoader, new Supplier[T]() {
+      override def get(): T = func.apply(shimsClassLoader)
+    })
```
Comment (1996fanrui) [inline streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala]:
```suggestion
    ClassLoaderUtils.runAsClassLoader[T](shimsClassLoader, () => func(shimsClassLoader))
```

This can be simplify.

File: streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala [hunk 9]
```diff
@@ -81,59 +83,106 @@ object FlinkShimsProxy extends Logger {
...
 
-  private[this] def getFlinkShimsClassLoader(flinkVersion: FlinkVersion): ClassLoader = {
+  // flink 1.12 1.13~1.14 1.15 parseSql class exist in different dependencies,
+  //need to load all flink-table dependencies compatible with different versions
+  def getVerifySqlLibClassLoader(flinkVersion: FlinkVersion): ClassLoader = {
+    logInfo(s"add  verify sql lib,flink version:  $flinkVersion")
+    VERIFY_SQL_CLASS_LOADER_CACHE.getOrElseUpdate(s"${flinkVersion.fullVersion}", {
+      val getFlinkTable: File => Boolean = _.getName.startsWith("flink-table")
+      // 1) flink/lib/flink-table*
+      val libTableURL = getFlinkHomeLib(flinkVersion.flinkHome, "lib", getFlinkTable)
```
Comment (1996fanrui) [inline streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala:91]: As I understand, we should exclude the `lib/flink-table-planner*`, right?

File: streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala [hunk 10]
```diff
@@ -81,59 +83,106 @@ object FlinkShimsProxy extends Logger {
...
+      addShimsUrls(flinkVersion, shimsUrls, _.getName.startsWith("streampark-flink-shims"))
+      new ChildFirstClassLoader(
+        shimsUrls.toArray,
+        Thread.currentThread().getContextClassLoader,
+        getFlinkShimsResourcePattern(flinkVersion.majorVersion)
+      )
+    })
+  }
+
+  def addShimsUrls(flinkVersion: FlinkVersion, shimsUrls: ListBuffer[URL], filterJar: File => Boolean): Unit = {
```
Comment (1996fanrui) [inline streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala]:
```suggestion
  def addShimsUrls(flinkVersion: FlinkVersion, addShimUrl: File => Unit): Unit = {
```

How about define the addShimUrl directly, and delete old addShimUrl?

getVerifySqlLibClassLoader caller:
```
      addShimsUrls(flinkVersion, file => {
        if (file.getName.startsWith("streampark-flink-shims")) {
          shimsUrls += file.toURI.toURL
        }
      })
```

getFlinkShimsClassLoader caller:
```
      addShimsUrls(flinkVersion, file => {
        shimsUrls += file.toURI.toURL
      })
```

File: streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala (hunk 9 above)
Comment (monrg) [reply streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala:91]: hi @1996fanrui  Thank you for your feedback.The module of the Flink dependence on SQL is the dependencies of Flink-Table. Different versions and names are different (1. 2 ~ 1.4 in the verification SQL in LIB, 1.15 in OPT, and the dependencies are inconsistent) To compatible with different board versions, the same is used by the prefix Flink-Table to filter the required files.

File: streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala (hunk 10 above)
Comment (monrg) [reply streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala]: hi @1996fanrui  Thank you for your feedback.  Verifying sql dependencies also requires several classes in streampark's StreamPark-Flink-Shims module, so you need to add them as well

File: streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala [hunk 11]
```diff
@@ -81,59 +83,106 @@ object FlinkShimsProxy extends Logger {
...
+
+  /**
+   * Get ClassLoader to verify sql
+   *
+   * @param flinkVersion flinkVersion
+   * @param func         execute function
+   * @tparam T
+   * @return
+   */
+  def proxyVerifySql[T](flinkVersion: FlinkVersion, func: JavaFunc[ClassLoader, T]): T = {
```
Comment (wolfboys) [inline streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala:152]: Why do you need a new method?

Comment (monrg) [reply streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala:152]: hi, @wolfboys   Thank you for your feedback，Because after flink 1.15 flink-table-planner migrated to opt directory, streampark classloader failed to load the CalciteParser class, error when verify SQL script . nedd to add flink-table-planner to verify sql classloader classpath . but  ExecutorFactory has two implementation: DefaultExecutorFactory(flink-table-planer) and DelegateExecutorFactory(flink-table-planer-loader), spi load 2 servi will conflict, 
so i add a new method to separate the verify sql from the classloader of the submitted job, compatible with multiple versions to get the check sql dependency to create a new classloader

File: streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala (hunk 10 above)
Comment (1996fanrui) [reply streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala]: As I understand, this comment just refactor, not change the logic, right?

Comment (monrg) [reply streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala]: no, it's add a new logic. added to generate only the sql classloader, does not change the classloader for submitting jobs. Modifications were made to the common code during development that looked like refactoring.

File: streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala (hunk 11 above)
Comment (wolfboys) [reply streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala:152]: > hi, @wolfboys Thank you for your feedback，Because after flink 1.15 flink-table-planner migrated to opt directory, streampark classloader failed to load the CalciteParser class, error when verify SQL script . nedd to add flink-table-planner to verify sql classloader classpath . but ExecutorFactory has two implementation: DefaultExecutorFactory(flink-table-planer) and DelegateExecutorFactory(flink-table-planer-loader), spi load 2 servi will conflict, so i add a new method to separate the verify sql from the classloader of the submitted job, compatible with multiple versions to get the check sql dependency to create a new classloader

good job, Thanks for your hard work, I'll review later

File: streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala (hunk 10 above)
Comment (monrg) [reply streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala]: hi @1996fanrui i refactor it !

**Review by 1996fanrui — APPROVED** [review]
Hi @monrg , thanks for your contribution. 

LGTM

Hi @wolfboys , please help double check in your free time, thanks~

**Review by wolfboys — APPROVED** [review]
LGTM
