### PR TITLE
[Bug] Fix the help when user/role name already exists

### LINKED ISSUE #1634: [Bug] The help is wrong when submit user/role
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

The help should be `抱歉，该用户名已存在`, but the help is `用户名不能为空`.

image

The help should be `抱歉，该角色名称已存在`, but the help is `角色名称不能为空`.

image

Root cause:

When click the submit and `this.validateStatus !== 'success'`, it call the `handleRoleNameBlur()` and without any args. So the help is changed to the `角色名称不能为空`.

Solution: we shouldn't call the `handleRoleNameBlur()` when click the submit and `this.validateStatus !== 'success'`, it has been updated before.

image

image

### StreamPark Version

The latest dev branch

### Java Version

_No response_

### Flink Version

all

### Scala Version of Flink

all

### Error Exception

```log
*
```

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by 1996fanrui**
### What problem does this PR solve?

Issue Number: close #1634 

Problem Summary:

The help should be `抱歉，该用户名已存在`, but the help is `用户名不能为空`.

image

The help should be `抱歉，该角色名称已存在`, but the help is `角色名称不能为空`.

image

The help is right with this PR.

image

### What is changed and how it works?

Proposal: [xxx](url) 

Feel free to ping committers for the review!

## Contribution Checklist

  - Make sure that the pull request corresponds to a [GITHUB issue](https://github.com/apache/streampark/issues).

  - Name the pull request in the form "[Feature] [component] Title of the pull request", where *Feature* can be replaced by `Hotfix`, `Bug`, etc.

  - Minor fixes should be named following this pattern: `[hotfix] [docs] Fix typo in README.md doc`.

## Purpose of this pull request

Fix the help when user/role name already exists

### CODE REVIEW

File: streampark-console/streampark-console-webapp/src/views/system/role/RoleAdd.vue [hunk 1]
```diff
@@ -161,14 +161,12 @@ export default {
     },
     handleSubmit () {
       const checkedArr = this.selectedKeysAndHalfCheckedKeys
-      if (this.validateStatus !== 'success') {
-        this.handleRoleNameBlur()
-      } else if (checkedArr.length === 0) {
+      if (checkedArr.length === 0) {
         this.menuSelectStatus = 'error'
         this.menuSelectHelp = '请选择相应的权限'
```
Comment (wolfboys) [inline streampark-console/streampark-console-webapp/src/views/system/role/RoleAdd.vue]: can be changed to English.

Comment (1996fanrui) [reply streampark-console/streampark-console-webapp/src/views/system/role/RoleAdd.vue]: Thanks for your review, updated.

**Review by wolfboys — APPROVED** [review]
LGTM
