### PR TITLE
[Fix-519]: add the soft link checking for flink home. (#519)

### LINKED ISSUE #519: [Bug] Use symbolic link of flink home, couldn't deploy to yarn application cluster
*Please answer these questions before submitting your issue. Thanks!*

### Environment Description
* **StreamX Version**: 1.2.1 (main brach)
* **JVM version** (`java -version`): 1.8
* **OS version** (`uname -a` if on a Unix-like system): macOS

### Bug Description
When setting a symbolic link of flink home at Setting -> Flink Home panel, couldn't deploy to yarn application cluster.

### How to Reproduce 
1. create symbolic link for your flink home, like "ln -s flink-1.12.5 flink"
2. go to Setting -> Flink Home panel, create a default flink home setting use the symbolic link

### Additional context
When i deploy a flink sql task to yarn application cluser, it throws the following exception: couldn't find flink lib dir on streamx home.

image
image

### PR DESCRIPTION
**Pull request by lvshaokang**
### What problem does this PR solve?

Issue Number: close #519  

### What is changed and how it works?

What's Changed: add the soft link checking for flink home

How it Works: not allowed to set a soft link path as flink home

### CODE REVIEW

**Comment by wolfboys** [comment]
when using the path, it may be a better way to deal with it compatible

File: streamx-common/src/main/scala/com/streamxhub/streamx/common/domain/FlinkVersion.scala [hunk 1]
```diff
@@ -50,7 +51,8 @@ class FlinkVersion(val flinkHome: String) extends java.io.Serializable {
 
   lazy val flinkLib: File = {
     require(flinkHome != null, "[StreamX] flinkHome must not be null.")
-    require(new File(flinkHome).exists(), "[StreamX] flinkHome must be exists.")
+    val home = new File(flinkHome)
+    require(home.exists(), "[StreamX] flinkHome must be exists.")
```
Comment (wolfboys) [inline streamx-common/src/main/scala/com/streamxhub/streamx/common/domain/FlinkVersion.scala]: require(new File(flinkHome).exists(), "[StreamX] flinkHome must be exists.") 

is better?

**Review by wolfboys — COMMENTED** [review]
LGTM.

**Review by wolfboys — APPROVED** [review]
