### PR TITLE
[ISSUES-3667] KubernetesClusterDescriptor not closed after use, cause the file handle resource leaks

### LINKED ISSUE #3667: [Bug] KubernetesClusterDescriptor not closed after use, cause the file handle resource leaks
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

jdk-8

### Scala Version

2.12.x

### StreamPark Version

release-2.1.2

### Flink Version

flink-1.18.1

### deploy mode

kubernetes-application

### What happened

KubernetesClusterDescriptor not closed after use, cause the file handle resource leaks, file handle more than after the file handle system Settings, following a series of and open the file all related function abnormal, affect the use of the system

Change the corresponding code in newFlinkClusterClient in KubernetesRetriever
Original code
```    
Try {
      clusterProvider
        .retrieve(flinkConfig.getString(KubernetesConfigOptions.CLUSTER_ID))
        .getClusterClient
    } match {
      case Success(v) => Some(v)
      case Failure(e) =>
        logError(s"Get flinkClient error, the error is: $e")
        None
    }
```
modified
```  
 try {
      Try {
        clusterProvider
          .retrieve(flinkConfig.getString(KubernetesConfigOptions.CLUSTER_ID))
          .getClusterClient
      } match {
        case Success(v) => Some(v)
        case Failure(e) =>
          logError(s"Get flinkClient error, the error is: $e")
          None
      }
    } finally {
      Utils.close(clusterProvider)
    }
```

### Error Exception

_No response_

### Screenshots

image

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by jianjun159**
## What changes were proposed in this pull request

Issue Number: close #3667 

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (yes / no)

### CODE REVIEW

File: streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/KubernetesRetriever.scala [hunk 1]
```diff
@@ -89,15 +89,19 @@ object KubernetesRetriever extends Logger {
...
-    Try {
-      clusterProvider
-        .retrieve(flinkConfig.getString(KubernetesConfigOptions.CLUSTER_ID))
-        .getClusterClient
-    } match {
-      case Success(v) => Some(v)
-      case Failure(e) =>
-        logError(s"Get flinkClient error, the error is: $e")
-        None
+    try {
```
Comment (wolfboys) [inline streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/KubernetesRetriever.scala]: Can you test the improved code below? If it can pass the test, it is recommended to use the following code

```scala
// retrieve flink cluster client
  clusterClientServiceLoader
    .getClusterClientFactory(flinkConfig)
    .createClusterDescriptor(flinkConfig)
    .asInstanceOf[KubernetesClusterDescriptor]
    .autoClose {
      clusterProvider =>
        Try {
          clusterProvider
            .retrieve(flinkConfig.getString(KubernetesConfigOptions.CLUSTER_ID))
            .getClusterClient
        } match {
          case Success(v) => Some(v)
          case Failure(e) =>
            logError(s"Get flinkClient error, the error is: $e")
            None
        }
    }

```

Comment (caicancai) [reply streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/KubernetesRetriever.scala]: +1

**Review by wolfboys — APPROVED** [review]
LGTM

**Review by caicancai — APPROVED** [review]
LGTM
