### PR TITLE
[ISSUE-3405][Feature] Avoid Null Pointer Exception in switch keyword

### LINKED ISSUE #3405: [Feature] Avoid Null Pointer Exception in Switch keyword
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

**Switch used**
switch使用2023-12-18 111933

---------------------------------------------------------------------------------------

**call**

中间调用2023-12-18 112141

---------------------------------------------------------------------------------------

**may return null**

屏幕截图 2023-12-18 112838

### Usage Scenario

maybe we can use UNKONW to repalce NULL
---------------------------------------------------------------------------------------
改进 2023-12-18 114215

### Related issues

_No response_

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhengkezhou1**
## What changes were proposed in this pull request

Issue Number: close #3405 

## Brief change log
- *modify **org/apache/streampark/common/enums/ApplicationType.java***
- *modify **org/apache/streampark/common/enums/FlinkDevelopmentMode.java***
- *modify **org/apache/streampark/common/enums/FlinkExecutionMode.java***

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (**no**)

### CODE REVIEW

**Comment by caicancai** [comment]
cc @RocMarshal Thank you for your contribution，good job

**Review by caicancai — APPROVED** [review]

File: streampark-common/src/main/java/org/apache/streampark/common/enums/ApplicationType.java [hunk 1]
```diff
@@ -32,7 +31,10 @@ public enum ApplicationType {
   STREAMPARK_SPARK(3, "StreamPark Spark"),
 
   /** Apache Spark */
-  APACHE_SPARK(4, "Apache Spark");
+  APACHE_SPARK(4, "Apache Spark"),
+
+  /** Unknown type replace null */
+  UNKNOWN(5, "unknown");
```
Comment (wolfboys) [inline streampark-common/src/main/java/org/apache/streampark/common/enums/ApplicationType.java]: I agree to add a new type "UNKNOWN", but I have a suggestion regarding the value. I recommend setting the value as -1. Currently, the value is 5. If we add another engine type in the future, it may cause trouble.

File: streampark-common/src/main/java/org/apache/streampark/common/enums/FlinkExecutionMode.java [hunk 2]
```diff
@@ -45,8 +45,10 @@ public enum FlinkExecutionMode {
   KUBERNETES_NATIVE_SESSION(5, "kubernetes-session"),
 
   /** kubernetes application */
-  KUBERNETES_NATIVE_APPLICATION(6, "kubernetes-application");
+  KUBERNETES_NATIVE_APPLICATION(6, "kubernetes-application"),
 
+  /** Unknown Mode */
+  UNKNOWN(7, "Unknown");
```
Comment (wolfboys) [inline streampark-common/src/main/java/org/apache/streampark/common/enums/FlinkExecutionMode.java]: I suggest changing the value to -1.

File: streampark-common/src/main/java/org/apache/streampark/common/enums/ApplicationType.java (hunk 1 above)
Comment (RocMarshal) [reply streampark-common/src/main/java/org/apache/streampark/common/enums/ApplicationType.java]: +1

File: streampark-common/src/main/java/org/apache/streampark/common/enums/FlinkExecutionMode.java (hunk 2 above)
Comment (zhengkezhou1) [reply streampark-common/src/main/java/org/apache/streampark/common/enums/FlinkExecutionMode.java]: @wolfboys changed

**Review by wolfboys — APPROVED** [review]
LGTM
