### PR TITLE
[Bug]should not set clusterId for application from appParam when update job

### LINKED ISSUE #4075: [Bug] update running job, will set job clusterId to null, leading to Streampark cannot get status for the job
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.11.x

### StreamPark Version

dev

### Flink Version

1.16.2

### deploy mode

yarn-application

### What happened

deploy mode:
yarn application
yarn session

below is the  error example for yarn application mode
1. a running job
image
job cluster_id is application_1726758048768_39519
image

2. update job and submit

image
flink/app/update controller did not pass clusterId during update job
image

after update job， job cluster_id is set to null
image

3.  stop  the job

the job stoped failed
image

error stack
```
java.util.concurrent.CompletionException: java.lang.reflect.InvocationTargetException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.streampark.flink.client.FlinkClient$.$anonfun$proxy$1(FlinkClient.scala:89)
	at org.apache.streampark.flink.proxy.FlinkShimsProxy$.$anonfun$proxy$1(FlinkShimsProxy.scala:72)
	at org.apache.streampark.common.util.ClassLoaderUtils$.runAsClassLoader(ClassLoaderUtils.scala:44)
	at org.apache.streampark.flink.proxy.FlinkShimsProxy$.proxy(FlinkShimsProxy.scala:72)
	at org.apache.streampark.flink.client.FlinkClient$.proxy(FlinkClient.scala:84)
	at org.apache.streampark.flink.client.FlinkClient$.cancel(FlinkClient.scala:62)
	at org.apache.streampark.flink.client.FlinkClient.cancel(FlinkClient.scala)
	at org.apache.streampark.console.core.service.application.impl.ApplicationActionServiceImpl.lambda$cancel$0(ApplicationActionServiceImpl.java:314)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	... 3 more
Caused by: java.lang.IllegalArgumentException: [StreamPark] getClusterClient error. No cluster id was specified. Please specify a cluster to which you would like to connect.
	at org.apache.streampark.common.util.AssertUtils$.required(AssertUtils.scala:59)
	at org.apache.streampark.flink.client.trait.YarnClientTrait.executeClientAction(YarnClientTrait.scala:59)
	at org.apache.streampark.flink.client.trait.YarnClientTrait.doCancel(YarnClientTrait.scala:90)
	at org.apache.streampark.flink.client.trait.YarnClientTrait.doCancel$(YarnClientTrait.scala:86)
	at org.apache.streampark.flink.client.impl.YarnApplicationClient$.doCancel(YarnApplicationClient.scala:47)
	at org.apache.streampark.flink.client.trait.FlinkClientTrait.cancel(FlinkClientTrait.scala:229)
	at org.apache.streampark.flink.client.trait.FlinkClientTrait.cancel$(FlinkClientTrait.scala:212)
	at org.apache.streampark.flink.client.impl.YarnApplicationClient$.cancel(YarnApplicationClient.scala:47)
	at org.apache.streampark.flink.client.FlinkClientEntrypoint$.cancel(FlinkClientEntrypoint.scala:48)
	at org.apache.streampark.flink.client.FlinkClientEntrypoint.cancel(FlinkClientEntrypoint.scala)
	... 16 more

```

### Error Exception

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by xieyi888**
## What changes were proposed in this pull request

Issue Number: close https://github.com/apache/incubator-streampark/issues/4075

## Brief change log
for org.apache.streampark.console.core.service.application.impl.ApplicationManageServiceImpl#update, 
1) should not set clusterId for application from appParam
2) should set flinkClusterId for YARN_SESSION mode

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.
no

This change is already covered by existing tests, such as *(please describe tests)*.
no

This change added tests and can be verified as follows:
Manually verified the change by testing locally

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (yes / no)

### CODE REVIEW

File: streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationManageServiceImpl.java [hunk 1]
```diff
@@ -527,7 +527,6 @@ public boolean update(Application appParam) {
         application.setDynamicProperties(appParam.getDynamicProperties());
         application.setResolveOrder(appParam.getResolveOrder());
         application.setExecutionMode(appParam.getExecutionMode());
-        application.setClusterId(appParam.getClusterId());
```
Comment (wolfboys) [inline streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationManageServiceImpl.java:530]: good job.

File: streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationManageServiceImpl.java [hunk 2]
```diff
@@ -559,6 +558,7 @@ public boolean update(Application appParam) {
                 break;
             case REMOTE:
             case YARN_SESSION:
+                application.setFlinkClusterId(appParam.getFlinkClusterId());
```
Comment (wolfboys) [inline streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationManageServiceImpl.java]: Oh no, there's no need to make changes here.

Comment (xieyi888) [reply streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationManageServiceImpl.java]: sorry, I had made a mistake here

**Review by wolfboys — APPROVED** [review]
