### PR TITLE
[FIX] fix ingrress to flink ui static resources 404

### LINKED ISSUE #3301: [Bug] Accessing Flink UI through ingress, static resources is 404
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

_No response_

### Scala Version

2.11.x

### StreamPark Version

2.1.1

### Flink Version

1.14.4

### deploy mode

kubernetes-application

### What happened

Accessing Flink UI through ingress, static resources is 404 
**1. config k8s Ingress** 

图片

**2. Accessing Flink UI through ingress, static resources is 404 ，eg. runtime-es2015.43504a5580dcf7b05dde.js 、/styles.f4012744d25b041a3257.css**

图片

**3. View current task ingrress resources**
图片

### Error Exception

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by 531651225**
## What changes were proposed in this pull request
refer to https://github.com/apache/incubator-streampark/issues/3301
Issue Number: close #3301 

## Verifying this change
This change added tests and can be verified as follows:
1.add nginx.ingress.kubernetes.io/configuration-snippet:  sub_filter '<base href="./">' '<base href="/namespace/cluster_id/">';
2.add   ingressClassName: nginx 
image

- test and visite flink ui adress 
- 图片

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (no)

### CODE REVIEW

**Comment by wolfboys** [comment]
cc @Al-assad PTAL, thx

File: streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/ingress/IngressStrategy.scala [hunk 1]
```diff
@@ -47,11 +47,15 @@ trait IngressStrategy {
...
   }
 
-  def buildIngressAnnotations(clusterId: String): Map[String, String] = {
+  def buildIngressAnnotations(clusterId: String, namespace: String): Map[String, String] = {
     val annotations = Map(
       "nginx.ingress.kubernetes.io/rewrite-target" -> "/$2",
       "nginx.ingress.kubernetes.io/proxy-body-size" -> "1024m",
-      "nginx.ingress.kubernetes.io/configuration-snippet" -> ("rewrite ^(/" + clusterId + ")$ $1/ permanent;")
+      "nginx.ingress.kubernetes.io/configuration-snippet" -> ("rewrite ^(/" + clusterId + ")$ $1/ permanent;" + String
+        .format(
```
Comment (Al-assad) [inline streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/ingress/IngressStrategy.scala]: It can be made more concise by modifying it to:
```scala
"nginx.ingress.kubernetes.io/configuration-snippet" -> s"rewrite ^(/ $clusterId )$$ $$1/ permanent; sub_filter '<base href=\"./\">' '<base href=\"/$namespace/$clusterId/\">'; sub_filter_once off;" 
```

File: streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/ingress/IngressStrategyV1.scala [hunk 2]
```diff
@@ -55,11 +55,12 @@ class IngressStrategyV1 extends IngressStrategy {
         val ingress = new IngressBuilder()
           .withNewMetadata()
           .withName(clusterId)
-          .addToAnnotations(buildIngressAnnotations(clusterId).asJava)
+          .addToAnnotations(buildIngressAnnotations(clusterId, nameSpace).asJava)
           .addToLabels(buildIngressLabels(clusterId).asJava)
           .addToOwnerReferences(ownerReference) // Add OwnerReference
           .endMetadata()
           .withNewSpec()
+          .withIngressClassName("nginx")
```
Comment (Al-assad) [inline streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/ingress/IngressStrategyV1.scala]: I think there is no need to set the ingressClass forcibly. The default value of ingressClass is "". Kubernetes will choose the default ingressClass, which is "nginx" for many Kubernetes instances. However, there are also some special cases, such as the default ingress provided by some cloud providers for Kubernetes not being nginx.

**Review by Al-assad — CHANGES_REQUESTED** [review]

File: streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/ingress/IngressStrategyV1.scala (hunk 2 above)
Comment (531651225) [reply streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/ingress/IngressStrategyV1.scala]: THKS, i agree whith you. already fix it

File: streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/ingress/IngressStrategy.scala (hunk 1 above)
Comment (531651225) [reply streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/ingress/IngressStrategy.scala]: THKS,  already fix it. PTAL

**Review by Al-assad — APPROVED** [review]
Good job！
