### PR TITLE
[ISSUE-2940][Improve] enhance login password protection

### LINKED ISSUE #2940: [Bug] Don't savedown salted password for LDAP login
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8+

### Scala Version

2.11.x

### StreamPark Version

latest

### Flink Version

N/A

### deploy mode

None

### What happened

In current LDAP login, streampark will encrypt the password of user's LDAP account, and save down salted password into the database.
It's not a good practice to save it as it might not meet the security or audit requirements.

### Error Exception

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by saLeox**
## What changes were proposed in this pull request

Issue Number: close #2940
- Don't save the salted password in LDAP authentication;
- Don't allow to update login type when update user;
- Don't allow to reset password for user who doesn't sign in with password.

## Verifying this change

This change is a code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (no)

### CODE REVIEW

File: streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/security/impl/AuthenticatorImpl.java [hunk 1]
```diff
@@ -59,9 +59,11 @@ public User authenticate(String username, String password, String loginType) thr
 
   private User passwordAuthenticate(String username, String password) {
     User user = usersService.findByName(username);
-    if (user == null || user.getLoginType() != LoginType.PASSWORD) {
-      throw new ApiAlertException(
-          String.format("user [%s] does not exist or can not login with PASSWORD", username));
+    if (user == null) {
```
Comment (wolfboys) [inline streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/security/impl/AuthenticatorImpl.java:62]: This will cause a bug. In LDAP login mode, if the username doesn't exist when first login, a new user needs to be created. so. we can't simply throw an exception.

Comment (saLeox) [reply streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/security/impl/AuthenticatorImpl.java:62]: The `passwordAuthenticate` is used to authenticate the password login, where have to throw error when user doesn't exist, while `ldapAuthenticate` is used for ldap login, and we already have that logic to handle the new user add scenario. Thanks.

**Review by wolfboys — APPROVED** [review]
LGTM

File: streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/security/impl/AuthenticatorImpl.java (hunk 1 above)
Comment (wolfboys) [reply streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/security/impl/AuthenticatorImpl.java:62]: > The `passwordAuthenticate` is used to authenticate the password login, where have to throw error when user doesn't exist, while `ldapAuthenticate` is used for ldap login, and we already have that logic to handle the new user add scenario. Thanks.

Thank you for your clarification. looks good to me
