### PR TITLE
[Bug] MySQL script error: Specified key was too long; max key length is 767 bytes

### LINKED ISSUE #2674: [Bug] MySQL script error: Specified key was too long; max key length is 767 bytes
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

_No response_

### Scala Version

2.11.x

### StreamPark Version

2.1.0

### Flink Version

1.16

### deploy mode

None

### What happened

MySQL script error: Specified key was too long; max key length is 767 bytes

### Error Exception

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by muchunjin**
## What changes were proposed in this pull request

Issue Number: close #2674  

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (yes / no)

### CODE REVIEW

File: streampark-console/streampark-console-service/src/main/assembly/script/schema/mysql-schema.sql [hunk 1]
```diff
@@ -357,7 +357,7 @@ create table `t_setting` (
 drop table if exists `t_user`;
 create table `t_user` (
   `user_id` bigint not null auto_increment comment 'user id',
-  `username` varchar(255) collate utf8mb4_general_ci not null comment 'user name',
+  `username` varchar(50) collate utf8mb4_general_ci not null comment 'user name',
   `nick_name` varchar(50) collate utf8mb4_general_ci not null comment 'nick name',
   `salt` varchar(255) collate utf8mb4_general_ci default null comment 'salt',
```
Comment (wolfboys) [inline streampark-console/streampark-console-service/src/main/assembly/script/schema/mysql-schema.sql]: `salt` varchar(64)

File: streampark-console/streampark-console-service/src/main/assembly/script/schema/mysql-schema.sql [hunk 2]
```diff
@@ -357,7 +357,7 @@ create table `t_setting` (
...
   `password` varchar(128) collate utf8mb4_general_ci not null comment 'password',
```
Comment (wolfboys) [inline streampark-console/streampark-console-service/src/main/assembly/script/schema/mysql-schema.sql]: `password` varchar(64)

File: streampark-console/streampark-console-service/src/main/assembly/script/upgrade/pgsql/2.1.0.sql [hunk 3]
```diff
@@ -40,7 +40,7 @@ create sequence "public"."streampark_t_yarn_queue_id_seq" increment 1 start 1000
 create table "public"."t_yarn_queue" (
     "id" int8 not null default nextval('streampark_t_yarn_queue_id_seq'::regclass),
     "team_id" int8 not null,
-    "queue_label" varchar(255) not null collate "pg_catalog"."default",
+    "queue_label" varchar(150) not null collate "pg_catalog"."default",
     "description" varchar(512) collate "pg_catalog"."default",
```
Comment (wolfboys) [inline streampark-console/streampark-console-service/src/main/assembly/script/upgrade/pgsql/2.1.0.sql]: `description` varchar(256)

File: streampark-console/streampark-console-service/src/main/resources/db/schema-h2.sql [hunk 4]
```diff
@@ -454,7 +454,7 @@ drop table if exists `t_yarn_queue`;
 create table if not exists `t_yarn_queue` (
   `id` bigint generated by default as identity not null comment 'queue id',
   `team_id` bigint not null comment 'team id',
-  `queue_label` varchar(255) not null comment 'queue label expression',
+  `queue_label` varchar(150) not null comment 'queue label expression',
```
Comment (wolfboys) [inline streampark-console/streampark-console-service/src/main/resources/db/schema-h2.sql]: `queue_label` varchar(128)

**Review by wolfboys — APPROVED** [review]
LGTM
