### PR TITLE
fix Can't open k8s session cluster webUI #2248

### LINKED ISSUE #2248: [Bug] Can't open k8s session cluster webUI
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

+ When I start the Flink cluster successfully,I can't open FlinkWebUI by useing `view cluster detail` button.
+ I found that `t_ flink_ The cluster.address` field is null.
+ In project code，`FlinkClusterServiceImpl.start()` method, update `t_ flink_ The cluster.address`  only in yarn-session Mode。
```java
 if (deployResponse != null) {
        if (ExecutionMode.YARN_SESSION.equals(executionModeEnum)) {
          String address =
              YarnUtils.getRMWebAppURL() + "/proxy/" + deployResponse.clusterId() + "/";
          flinkCluster.setAddress(address);
        }
        flinkCluster.setClusterId(deployResponse.clusterId());
        flinkCluster.setClusterState(ClusterState.STARTED.getValue());
        flinkCluster.setException(null);
        updateById(flinkCluster);
        FlinkRESTAPIWatcher.removeFlinkCluster(flinkCluster);
      } else {
        throw new ApiAlertException(
            "deploy cluster failed, unknown reason，please check you params or StreamPark error log");
      }
```

### StreamPark Version

2.0.0

### Java Version

jdk1.8

### Flink Version

flink 1.14.5

### Scala Version of Flink

scala 2.11

### Error Exception

```log
none exception
```

### Screenshots

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by dyccode**
## What changes were proposed in this pull request

Issue Number: close #2248 

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (yes / no)

### CODE REVIEW

**Review by wolfboys — DISMISSED** [review]
LGTM

**Comment by wolfboys** [comment]
hi dyccode, there is a checkstyle issue, please fixed, you can run command:
```
mvn spotless:apply
```

File: streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkClusterServiceImpl.java [hunk 1]
```diff
@@ -178,6 +178,8 @@ public void start(FlinkCluster cluster) {
           String address =
               YarnUtils.getRMWebAppURL() + "/proxy/" + deployResponse.clusterId() + "/";
           flinkCluster.setAddress(address);
+        } else {
+            flinkCluster.setAddress(deployResponse.address());
```
Comment (RocMarshal) [inline streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkClusterServiceImpl.java]:
```suggestion
          flinkCluster.setAddress(deployResponse.address());
```

**Review by wolfboys — APPROVED** [review]
