### PR TITLE
[Bug] Fix the bug that latest team isn't changed when team is changed

### LINKED ISSUE #1833: [Bug] The latest team isn't changed when team is changed
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

The latest team isn't changed when team is changed.

### StreamPark Version

latest dev

### Java Version

_No response_

### Flink Version

all

### Scala Version of Flink

all

### Error Exception

```log
all
```

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by 1996fanrui**
## What changes were proposed in this pull request

Issue Number: close #1833 

Fix the bug that latest team isn't changed when team is changed

## Brief change log

Fix the bug that latest team isn't changed when team is changed

Root cause:

https://github.com/apache/incubator-streampark/blob/f43646ec0d65aea5d7d2847c2097aae9975f8f0d/streampark-console/streampark-console-webapp/src/components/tools/UserMenu.vue#L330

When the team is changed, `handleChangeTeam` will call the backend with the new teamId. However, `request.js` change the teamId to the old teamId.

Solution:

When the `data['teamId'] == null`, `request.js` can change the teamId.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): no

### CODE REVIEW

File: streampark-console/streampark-console-webapp/src/utils/request.js [hunk 1]
```diff
@@ -78,7 +78,7 @@ http.interceptors.request.use(config => {
       }
     }
     const teamId = sessionStorage.getItem(TEAM_ID)
-    if (teamId) {
+    if (data['teamId'] == null && teamId) {
```
Comment (wolfboys) [inline streampark-console/streampark-console-webapp/src/utils/request.js:81]: hi fanrui:
 I don't quite understand, can you explain why you want to change here?

Comment (1996fanrui) [reply streampark-console/streampark-console-webapp/src/utils/request.js:81]: Hi @wolfboys , thanks for your review. I have update the root cause in the PR description before, you can take a look.

Comment (wolfboys) [reply streampark-console/streampark-console-webapp/src/utils/request.js:81]: > Hi @wolfboys , thanks for your review. I have update the root cause in the PR description before, you can take a look.

thx

**Review by wolfboys — APPROVED** [review]
LGTM
