### PR TITLE
[bug] After optimizing the core parameter. job submit failed bug fix

### LINKED ISSUE #1815: [Bug] remote mode deployment exceptions
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened
Start la streampark on the docker container, and bind the session cluster, using remote mode for sql demo task submission
图片
The operation status is failure, click submit log to view
图片
图片
图片

### StreamPark Version

1.14

### Java Version

_No response_

### Flink Version

1.14.5

### Scala Version of Flink

2.12

### Error Exception

```log
java.util.concurrent.CompletionException: java.lang.reflect.InvocationTargetException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.streampark.flink.submit.FlinkSubmitter$.$anonfun$submit$1(FlinkSubmitter.scala:52)
	at org.apache.streampark.flink.proxy.FlinkShimsProxy$.$anonfun$proxy$1(FlinkShimsProxy.scala:66)
	at org.apache.streampark.common.util.ClassLoaderUtils$.runAsClassLoader(ClassLoaderUtils.scala:39)
	at org.apache.streampark.flink.proxy.FlinkShimsProxy$.proxy(FlinkShimsProxy.scala:66)
	at org.apache.streampark.flink.submit.FlinkSubmitter$.submit(FlinkSubmitter.scala:47)
	at org.apache.streampark.flink.submit.FlinkSubmitter.submit(FlinkSubmitter.scala)
	at org.apache.streampark.console.core.service.impl.ApplicationServiceImpl.lambda$start$7(ApplicationServiceImpl.java:1379)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	... 3 more
Caused by: org.apache.flink.client.program.ProgramInvocationException: The program caused an error: 

Classpath: [file:/opt/streampark_workspace/workspace/100000/streampark-flinkjob_Flink_SQL_Demo.jar]

System.out: (none)

System.err: (none)
	at org.apache.flink.client.program.PackagedProgramUtils.generateException(PackagedProgramUtils.java:264)
	at org.apache.flink.client.program.PackagedProgramUtils.getPipelineFromProgram(PackagedProgramUtils.java:172)
	at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:82)
	at org.apache.streampark.flink.submit.trait.FlinkSubmitTrait.getJobGraph(FlinkSubmitTrait.scala:177)
	at org.apache.streampark.flink.submit.trait.FlinkSubmitTrait.getJobGraph$(FlinkSubmitTrait.scala:160)
	at org.apache.streampark.flink.submit.impl.RemoteSubmit$.jobGraphSubmit(RemoteSubmit.scala:128)
	at org.apache.streampark.flink.submit.impl.RemoteSubmit$.$anonfun$doSubmit$2(RemoteSubmit.scala:58)
	at org.apache.streampark.flink.submit.trait.FlinkSubmitTrait.$anonfun$trySubmit$5(FlinkSubmitTrait.scala:150)
	at scala.util.Try$.apply(Try.scala:209)
	at org.apache.streampark.flink.submit.trait.FlinkSubmitTrait.$anonfun$trySubmit$3(FlinkSubmitTrait.scala:150)
	at scala.util.Failure.getOrElse(Try.scala:218)
	at org.apache.streampark.flink.submit.trait.FlinkSubmitTrait.trySubmit(FlinkSubmitTrait.scala:148)
	at org.apache.streampark.flink.submit.trait.FlinkSubmitTrait.trySubmit$(FlinkSubmitTrait.scala:140)
	at org.apache.streampark.flink.submit.impl.RemoteSubmit$.doSubmit(RemoteSubmit.scala:58)
	at org.apache.streampark.flink.submit.trait.FlinkSubmitTrait.submit(FlinkSubmitTrait.scala:110)
	at org.apache.streampark.flink.submit.trait.FlinkSubmitTrait.submit$(FlinkSubmitTrait.scala:60)
	at org.apache.streampark.flink.submit.impl.RemoteSubmit$.submit(RemoteSubmit.scala:37)
	at org.apache.streampark.flink.submit.FlinkSubmit$.submit(FlinkSubmit.scala:29)
	at org.apache.streampark.flink.submit.FlinkSubmit.submit(FlinkSubmit.scala)
	... 15 more
Caused by: java.lang.ExceptionInInitializerError: [StreamPark] Usage:can't fond config,please set "--conf $path " in main arguments
	at org.apache.streampark.flink.core.FlinkStreamingInitializer.initParameter(FlinkStreamingInitializer.scala:126)
	at org.apache.streampark.flink.core.FlinkTableInitializer.initParameter(FlinkTableInitializer.scala:134)
	at org.apache.streampark.flink.core.FlinkStreamingInitializer.x$1$lzycompute(FlinkStreamingInitializer.scala:76)
	at org.apache.streampark.flink.core.FlinkStreamingInitializer.x$1(FlinkStreamingInitializer.scala:76)
	at org.apache.streampark.flink.core.FlinkStreamingInitializer.userParameter$lzycompute(FlinkStreamingInitializer.scala:76)
	at org.apache.streampark.flink.core.FlinkStreamingInitializer.userParameter(FlinkStreamingInitializer.scala:76)
	at org.apache.streampark.flink.core.FlinkTableInitializer.$anonfun$initEnvironment$1(FlinkTableInitializer.scala:155)
	at scala.util.Try$.apply(Try.scala:209)
	at org.apache.streampark.flink.core.FlinkTableInitializer.initEnvironment(FlinkTableInitializer.scala:155)
	at org.apache.streampark.flink.core.FlinkTableInitializer$.initialize(FlinkTableInitializer.scala:77)
	at org.apache.streampark.flink.core.scala.FlinkStreamTable.init(FlinkStreamTable.scala:54)
	at org.apache.streampark.flink.core.scala.FlinkStreamTable.main(FlinkStreamTable.scala:45)
	at org.apache.streampark.flink.core.scala.FlinkStreamTable.main$(FlinkStreamTable.scala:44)
	at org.apache.streampark.flink.cli.SqlClient$StreamSqlApp$.main(SqlClient.scala:63)
	at org.apache.streampark.flink.cli.SqlClient$.delayedEndpoint$org$apache$streampark$flink$cli$SqlClient$1(SqlClient.scala:55)
	at org.apache.streampark.flink.cli.SqlClient$delayedInit$body.apply(SqlClient.scala:30)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at org.apache.streampark.flink.cli.SqlClient$.main(SqlClient.scala:30)
	at org.apache.streampark.flink.cli.SqlClient.main(SqlClient.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
	at org.apache.flink.client.program.PackagedProgramUtils.getPipelineFromProgram(PackagedProgramUtils.java:158)
	... 32 more
```

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by wolfboys**
[buf] After optimiton the core parameter. job submit failed bug fix

## Contribution Checklist

After optimizing the core parameter(https://github.com/apache/incubator-streampark/pull/1774) job submit failed bug fix.

## What changes were proposed in this pull request

Issue Number: close #1815 

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (yes / no)

### CODE REVIEW

File: streampark-flink/streampark-flink-shims/streampark-flink-shims-base/src/main/scala/org/apache/streampark/flink/core/FlinkTableInitializer.scala [hunk 1]
```diff
@@ -127,50 +127,62 @@ private[flink] class FlinkTableInitializer(args: Array[String], apiType: ApiType
...
-      case PlannerType.any =>
-        logInfo("anyPlanner will be use.")
-        builder.useAnyPlanner()
+    val plannerType = Try(PlannerType.withName(parameter.get(KEY_FLINK_TABLE_PLANNER))).getOrElse(PlannerType.blink)
+
+    try {
+      plannerType match {
+        case PlannerType.blink =>
+          logInfo("blinkPlanner will be use.")
+          builder.useBlinkPlanner()
```
Comment (1996fanrui) [inline streampark-flink/streampark-flink-shims/streampark-flink-shims-base/src/main/scala/org/apache/streampark/flink/core/FlinkTableInitializer.scala:173]: As I know, Flink-1.15 removed this method. Blink planner is the default planner.

File: streampark-flink/streampark-flink-shims/streampark-flink-shims-base/src/main/scala/org/apache/streampark/flink/core/FlinkTableInitializer.scala [hunk 2]
```diff
@@ -127,50 +127,62 @@ private[flink] class FlinkTableInitializer(args: Array[String], apiType: ApiType
...
+        case PlannerType.old =>
+          logInfo("oldPlanner will be use.")
+          builder.useOldPlanner()
+        case PlannerType.any =>
+          logInfo("anyPlanner will be use.")
+          builder.useAnyPlanner()
+      }
+    } catch {
+      case e: IncompatibleClassChangeError =>
```
Comment (1996fanrui) [inline streampark-flink/streampark-flink-shims/streampark-flink-shims-base/src/main/scala/org/apache/streampark/flink/core/FlinkTableInitializer.scala:182]: After Flink 1.14, blink planner as the default planner. So Flink 1.12 and 1.13 has the `useBlinkPlanner ` method, but Flink 1.14 and 1.15 don't have the method.

Currently, this PR use the `try catch IncompatibleClassChangeError ` to be compatible with this problem. From the code specification, it is not reasonable. In the long term, it is very difficult to maintain.


We need a general code specification: How to adapt methods that are incompatible with each Flink version?

Comment (wolfboys) [reply streampark-flink/streampark-flink-shims/streampark-flink-shims-base/src/main/scala/org/apache/streampark/flink/core/FlinkTableInitializer.scala:182]: The API related to flink table env is public and stable, in the short term, only this part will be affected, in the long term, as you said, we need a set of standard specifications to solve these problems, How about you take care of this part of the job? Discuss it fully in the email. It can be done in several steps.

Comment (1996fanrui) [reply streampark-flink/streampark-flink-shims/streampark-flink-shims-base/src/main/scala/org/apache/streampark/flink/core/FlinkTableInitializer.scala:182]: Got it, I can do it in the future.

**Review by 1996fanrui — APPROVED** [review]
@wolfboys Thanks for your contribution.

LGTM

**Review by xinzhuxiansheng — APPROVED** [review]
LGTM！
