### PR TITLE
[Fix-3805] Remove redundant values in table `t_flink_app` insert statement

### LINKED ISSUE #3805: [Bug] Value Count Mismatch in INSERT Statement for `t_flink_app` Table in MySQL Initialization Script
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

_No response_

### Scala Version

2.12.x

### StreamPark Version

dev

### Flink Version

none 

### deploy mode

None

### What happened

Error Encountered During MySQL DB Initialization Script Execution: Value Count Mismatch in INSERT Statement for `t_flink_app` Table When Replacing H2 DB.

### Error Exception

_No response_

### Screenshots

屏幕截图 2024-06-25 221405
屏幕截图 2024-06-25 222308

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhengkezhou1**
## What changes were proposed in this pull request
The dml of table `t_flink_app` in existing H2, MySQL, PGSQL does not match the dll struct.

Issue Number: close #3805

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (no)

### CODE REVIEW

File: streampark-console/streampark-console-service/src/main/assembly/script/data/mysql-data.sql [hunk 1]
```diff
@@ -30,7 +30,12 @@ insert into `t_team` values (100000, 'default', null, now(), now());
 -- ----------------------------
 -- Records of t_flink_app
 -- ----------------------------
-insert into `t_flink_app` values (100000, 100000, 2, 4, null, null, 'Flink SQL Demo', null, null, null, null, null, null , null, 100000, null, 1, null, null, null, null, null, null, null, null, 0, 0, null, null, null, null, null, null, 'Flink SQL Demo', 0, null, null, null, null, null, null, null, 0, 0, now(), now(), null, 1, 1, null, null, null, null, null, null, 0, null, null, null, 'streampark,test', 0, null);
```
Comment (wolfboys) [inline streampark-console/streampark-console-service/src/main/assembly/script/data/mysql-data.sql:33]: I suggest using `insert table $table($column1,$column2,$column3)
values(...)` instead of `insert into $table values(...)` it is a better solution

File: streampark-console/streampark-console-service/src/main/assembly/script/data/mysql-data.sql [hunk 2]
```diff
@@ -30,7 +30,11 @@ insert into `t_team` values (100000, 'default', null, now(), now());
...
+INSERT INTO `t_flink_app` (
+    `id`, `team_id`, `job_type`, `execution_mode`, `job_name`, `user_id`, `app_type`, `state`, `restart_size`,
+    `description`,`resolve_order`,`option_state`,`tracking`,`create_time`, `modify_time`,`release`, `build`,
+    `k8s_hadoop_integration`,`tags`, `hadoop_user`
+) VALUES (100000, 100000, 2, 4, 'Flink SQL Demo', 100000, 1, 0, 0, 'Flink SQL Demo', 0, 0, 0, now(), now(), 1, 1, 0, 'streampark,test', 0);
```
Comment (wolfboys) [inline streampark-console/streampark-console-service/src/main/assembly/script/data/mysql-data.sql]: hadoop_user : 0 ?

**Review by wolfboys — APPROVED** [review]
LGTM
