### PR TITLE
[Fix] Fix submit to k8s retry and timeout too less.

### LINKED ISSUE #3388: [Bug] After k8s submit fail, submit again cause  once submit multi-jobs.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.11.x

### StreamPark Version

2.1.2

### Flink Version

1.16

### deploy mode

kubernetes-application

### What happened

I guess I submit failed, real jobs had been submitted, but streampark did not get the running jobs state.

### Error Exception

_No response_

### Screenshots

image
image

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by minchowang**
## What changes were proposed in this pull request

Issue Number: close #3388 

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): no

### CODE REVIEW

**Comment by minchowang** [comment]
https://github.com/apache/flink/blob/aa5766e257a8b40e15d08eafa1e005837694772b/flink-core/src/main/java/org/apache/flink/configuration/RestOptions.java#L128C1-L134C60 


In the `RestOptions.java`, RETRY_MAX_ATTEMPTS default value is 20,  It is more than streampark RETRY_MAX_ATTEMPTS default value `2`, it might cause streampark show submit failed, but already submit to k8s.

**Comment by caicancai** [comment]
cc @Al-assad

File: streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/KubernetesRetriever.scala [hunk 1]
```diff
@@ -41,11 +41,11 @@ import scala.util.{Failure, Success, Try}
...
 
   // see org.apache.flink.client.cli.ClientOptions.CLIENT_TIMEOUT}
-  val FLINK_CLIENT_TIMEOUT_SEC = 30L
+  val FLINK_CLIENT_TIMEOUT_SEC = 60L
   // see org.apache.flink.configuration.RestOptions.AWAIT_LEADER_TIMEOUT
-  val FLINK_REST_AWAIT_TIMEOUT_SEC = 10L
+  val FLINK_REST_AWAIT_TIMEOUT_SEC = 30L
   // see org.apache.flink.configuration.RestOptions.RETRY_MAX_ATTEMPTS
-  val FLINK_REST_RETRY_MAX_ATTEMPTS = 2
+  val FLINK_REST_RETRY_MAX_ATTEMPTS = 30
```
Comment (Al-assad) [inline streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/KubernetesRetriever.scala:48]: I think it would be better to change it to 20, the default value of RestOptions.RETRY_MAX_ATTEMPTS.

Comment (minchowang) [reply streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/KubernetesRetriever.scala:48]: > I think it would be better to change it to 20, the default value of RestOptions.RETRY_MAX_ATTEMPTS.

I think the redundant number of times can cover unknown issues.

Comment (Al-assad) [reply streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/KubernetesRetriever.scala:48]: I agree with you that this part affects flink task deployment and state tracking, and the state tracking part has its own additional timeout control mechanism, and increasing the retry parameter does alleviate the timeout tolerance of the submitted job.
So, LGTM

**Review by Al-assad — APPROVED** [review]
LGTM
